# Generated by Django 3.2.7 on 2021-11-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productscategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this product should be treated as active. Unselect this instead of product accounts.', verbose_name='active'),
        ),
    ]
